# Generated by Django 4.2.3 on 2023-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_details',
            old_name='checksum',
            new_name='requested_checksum',
        ),
        migrations.AddField(
            model_name='payment_details',
            name='responsed_checksum',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
